const config = {
  markerScale: 0.01,
  tooltipMinWidth: 380,
  imagePaths: {
    debug: "./kubesec-diagram.svg",
    production:
      "https://raw.githubusercontent.com/kubesec-diagram/kubesec-diagram.github.io/refs/heads/main/kubesec-diagram.svg",
  },
  runtime: {
    // bundle: "./dist/app.bundle.js",
    bundle:
      "https://raw.githubusercontent.com/kubesec-diagram/kubesec-diagram.github.io/refs/heads/main/dist/app.bundle.js",
    bundleFallbackToModules: true,
    scripts: [
      "./src/url-state.js",
      "./src/tag-utils.js",
      "./src/tag-controls.js",
      "./src/tooltip.js",
      "./src/filter-layout.js",
      "./src/filter-panel-state.js",
      "./src/filter-panel-input.js",
      "./src/viewport.js",
      "./src/viewport-input.js",
      "./src/theme.js",
      "./src/content-utils.js",
      "./src/help-utils.js",
      "./src/filter-highlight.js",
      "./src/filter-results.js",
      "./src/user-annotation-positioning.js",
      "./src/user-annotation-forms.js",
      "./src/user-annotation-list.js",
      "./src/user-annotation-render.js",
      "./src/user-annotation-hover.js",
      "./src/user-annotation-drag.js",
      "./src/user-annotation-placement.js",
      "./src/user-annotation-init.js",
      "./src/load-feedback.js",
      "./src/app-lifecycle.js",
      "./src/svg-help.js",
      "./src/svg-loader.js",
      "./src/app.js",
    ],
    entryScript: "./src/app.js",
  },
  ui: {
    loadingIndicatorId: "loading-indicator",
    loadingMessage: "Loading diagram...",
    tooltipHideDelay: 100,
  },
  tagFilters: {
    groups: [
      { id: "priority", label: "Priority", order: 1 },
      { id: "general", label: "Tags", order: 10, disableHelpIfHidden: true },
    ],
    tags: {
      info: {
        label: "Info",
        group: "priority",
        order: 4,
        style: {
          background: "#DFF4FF",
          color: "#0A3D5A",
          borderColor: "#0B6FA4",
          borderWidth: "3px",
          fontWeight: "700",
        },
        panelStyle: {
          borderColor: "#0B6FA4",
          borderWidth: "3px",
          boxShadow: "inset 0 0 0 1px rgba(11, 111, 164, 0.42)",
        },
      },
      "pri-1": {
        label: "Priority 1",
        group: "priority",
        order: 1,
        style: {
          background: "#FF7A7A",
          color: "#5B1010",
          borderColor: "#7A1414",
          borderWidth: "3px",
          fontWeight: "700",
        },
        panelStyle: {
          borderColor: "#7A1414",
          borderWidth: "3px",
          boxShadow: "inset 0 0 0 1px rgba(122, 20, 20, 0.40)",
        },
      },
      "pri-2": {
        label: "Priority 2",
        group: "priority",
        order: 2,
        style: {
          background: "#FFD1A1",
          color: "#6B2F00",
          borderColor: "#B45F06",
          borderWidth: "3px",
          fontWeight: "700",
        },
        panelStyle: {
          borderColor: "#B45F06",
          borderWidth: "3px",
          boxShadow: "inset 0 0 0 1px rgba(180, 95, 6, 0.35)",
        },
      },
      "pri-3": {
        label: "Priority 3",
        group: "priority",
        order: 3,
        style: {
          background: "#FFF2A6",
          color: "#5C4300",
          borderColor: "#B68A00",
          borderWidth: "3px",
          fontWeight: "700",
        },
        panelStyle: {
          borderColor: "#B68A00",
          borderWidth: "3px",
          boxShadow: "inset 0 0 0 1px rgba(182, 138, 0, 0.35)",
        },
      },
    },
  },
  allowedHtmlTags: ["hr", "br", "b", "strong", "i", "em", "u"],
  htmlWhitelist: {
    hr: [],
    br: [],
    b: [],
    strong: [],
    i: [],
    em: [],
    u: [],
  },
  userAnnotationTypes: {
    "user-important": {
      bg: "#ff1744",
      color: "#fff",
      radius: "8px",
      border: "#d50000",
      borderWidth: "2px",
      borderStyle: "solid",
      label: "Red Solid",
      scale: 2.0,
      annotationType: "point",
    },
    "user-info": {
      bg: "#2196f3",
      color: "#fff",
      radius: "8px",
      border: "#1976d2",
      borderWidth: "3px",
      borderStyle: "dotted",
      label: "Blue Dotted",
      scale: 2.0,
      annotationType: "point",
    },
    "user-success": {
      bg: "#4caf50",
      color: "#fff",
      radius: "8px",
      border: "#2e7d32",
      borderWidth: "2px",
      borderStyle: "double",
      label: "Green Double",
      scale: 2.0,
      annotationType: "point",
    },
    "user-neutral": {
      bg: "#9e9e9e",
      color: "#fff",
      radius: "8px",
      border: "#424242",
      borderWidth: "1px",
      borderStyle: "solid",
      label: "Gray Thin",
      scale: 2.0,
      annotationType: "point",
    },
    "user-urgent": {
      bg: "#ff5722",
      color: "#fff",
      radius: "8px",
      border: "#d84315",
      borderWidth: "4px",
      borderStyle: "dashed",
      label: "Orange Urgent",
      scale: 2.0,
      annotationType: "point",
    },
    "area-important": {
      bg: "transparent",
      color: "#fff",
      border: "#ff1744",
      borderWidth: "2px",
      borderStyle: "solid",
      label: "Red Solid",
      annotationType: "area",
      defaultSize: { width: 150, height: 100 },
      minSize: { width: 50, height: 50 },
      maxSize: { width: 1200, height: 800 },
    },
    "area-info": {
      bg: "transparent",
      color: "#fff",
      border: "#2196f3",
      borderWidth: "3px",
      borderStyle: "dotted",
      label: "Blue Dotted",
      annotationType: "area",
      defaultSize: { width: 150, height: 100 },
      minSize: { width: 50, height: 50 },
      maxSize: { width: 1200, height: 800 },
    },
    "area-success": {
      bg: "transparent",
      color: "#fff",
      border: "#4caf50",
      borderWidth: "2px",
      borderStyle: "double",
      label: "Green Double",
      annotationType: "area",
      defaultSize: { width: 150, height: 100 },
      minSize: { width: 50, height: 50 },
      maxSize: { width: 1200, height: 800 },
    },
    "area-neutral": {
      bg: "transparent",
      color: "#fff",
      border: "#9e9e9e",
      borderWidth: "1px",
      borderStyle: "solid",
      label: "Gray Thin",
      annotationType: "area",
      defaultSize: { width: 150, height: 100 },
      minSize: { width: 50, height: 50 },
      maxSize: { width: 1200, height: 800 },
    },
    "area-urgent": {
      bg: "transparent",
      color: "#fff",
      border: "#ff5722",
      borderWidth: "4px",
      borderStyle: "dashed",
      label: "Orange Urgent",
      annotationType: "area",
      defaultSize: { width: 120, height: 120 },
      minSize: { width: 60, height: 60 },
      maxSize: { width: 1000, height: 1000 },
    },
    "user-warning": {
      bg: "#ffc107",
      color: "#000",
      radius: "8px",
      border: "#ff8f00",
      borderStyle: "dashed",
      borderWidth: "3px",
      label: "Yellow Dashed",
      scale: 2.0,
      annotationType: "point",
    },
    "user-critical": {
      bg: "#e91e63",
      color: "#fff",
      radius: "8px",
      border: "#ad1457",
      borderWidth: "5px",
      borderStyle: "solid",
      label: "Pink Thick",
      scale: 2.0,
      annotationType: "point",
    },
    "area-warning": {
      bg: "transparent",
      color: "#000",
      border: "#ffc107",
      borderStyle: "dashed",
      borderWidth: "3px",
      label: "Yellow Dashed",
      annotationType: "area",
      defaultSize: { width: 150, height: 100 },
      minSize: { width: 50, height: 50 },
      maxSize: { width: 1200, height: 800 },
    },
    "area-critical": {
      bg: "transparent",
      color: "#fff",
      border: "#e91e63",
      borderWidth: "5px",
      borderStyle: "solid",
      label: "Pink Thick",
      annotationType: "area",
      defaultSize: { width: 150, height: 100 },
      minSize: { width: 50, height: 50 },
      maxSize: { width: 1200, height: 800 },
    },
  },
  maxUserAnnotations: 10,
  areaAnnotationConfig: {
    borderWidth: 3,
    hoverBorderWidth: 4,
    resizeHandleSize: 8,
    minHoverDistance: 5, // pixels from border to trigger hover
  },
};
